version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container-name: todo-app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    networks:
      - todo-network

  postgres:
    image: postgres:18
    container_name: db_server
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: db_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network

volumes:
  postgres_data:
  
networks:
  todo-network:
    driver: bridge