services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app  # Fixed: underscore instead of hyphen
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql://postgresuser:postgrespassword@postgres:5432/db_postgres
      - NODE_ENV=development
      - CORS_URL=http://localhost:3000
    depends_on:
      - postgres
    networks:
      - todo-network

  postgres:
    image: postgres:18
    container_name: db_server
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: db_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network

volumes:
  postgres_data:
  
networks:
  todo-network:
    driver: bridge