version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: db_server
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: db_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: