service: nodejs-backend-api

useDotenv: true

stages:
  default:
    params:
      region: ap-south-1

provider:
  name: aws
  runtime: nodejs22.x
  region: ${param:region}
  memorySize: 512
  timeout: 29
  deploymentBucket:
    name: nodejs-backend-api-deployments-920191147366
  httpApi:
    cors: true
  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    CORS_URL: ${env:CORS_URL, '*'}
    LOG_DIR: /tmp/logs
    THUNDERMAIL_API_KEY: ${env:THUNDERMAIL_API_KEY}
    THUNDERMAIL_FROM: ${env:THUNDERMAIL_FROM, 'onboarding@thundermail.io'}
    AWS_S3_LOG_BUCKET_NAME: ${env:AWS_S3_LOG_BUCKET_NAME, ''}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID, ''}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET, ''}
    GOOGLE_REDIRECT_URI: ${env:GOOGLE_REDIRECT_URI, ''}
    GOOGLE_OAUTH_SCOPE: ${env:GOOGLE_OAUTH_SCOPE, 'openid email profile'}

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node22
    exclude:
      - '@aws-sdk/*'

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
    noPrependStageInUrl: true
